[package]
name = "rust-website"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4"
env_logger = "0.10"
actix-web = "4.10.2"
tokio = { version = "1.0", features = ["full"] }
actix-files = "0.6.2"